# Generated by Django 3.2.5 on 2022-06-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20220627_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullquestion',
            name='question',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
